name: aspnetcore_root_workflow
on:
  workflow_call:
    inputs:
      CLIENT:
        type: string
      CLIENT_ENV:
        type: string
      DOWNLOAD_PACKAGE:
        type: string
      DEPLOY_IIS:
        type: string
      SITE_NAME:
        type: string
      DOTNET_VERSION:
        type: string
      WEBDEPLOY_USER: 
        type: string
      SERVER_IP:
        type: string
      SERVER_PORT:
        type: string
      PROJECT_ROOT_DIRECTORY:
        type: string
      PROJECT_NAME:
        type: string
    secrets:
      NUGET_URL:
        required: true
      NUGET_TOKEN:
        required: true
      WEBDEPLOY_PASSWORD:
        required: true
jobs:
  Build-Package-IIS_Deploy:
    runs-on: windows-latest
    environment: 'Production'
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}
          source-url: ${{ secrets.NUGET_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
          
      - name: Build and publish
        run: dotnet publish ${{inputs.PROJECT_NAME}}\${{inputs.PROJECT_NAME}}.csproj --configuration Release -o ${{ env.DOTNET_ROOT}}/myapp /p:EnvironmentName=${{inputs.CLIENT}}${{inputs.CLIENT_ENV}}
  
      - name: Clean appsettings
        run: |
          cd ${{ env.DOTNET_ROOT}}\myapp
          $jsonFiles = Get-ChildItem appsettings*json
          foreach ($file in $jsonFiles) {
            if ($file.Name -inotcontains "appsettings.json") {
              if ($file.Name -inotcontains "appsettings.Config.json") {
                  if ($file.Name -inotcontains "appsettings.${{inputs.CLIENT_ENV}}.json"){
                  #Write-Host -id 3 -activity "Removing File $($file.Name)" -Status "In progress"
                  Write-Host "$(Get-Date -f $timeStampFormat) - Removing File $($file.Name): In progress"
                  Remove-Item $file
                }
              }     
            }   
          }          
          
      - name: encrpt appsetting
        if: ${{ inputs.CLIENT == 'Dfcu' }}
        shell: pwsh
        run: |
          git clone https://github.com/tmcoma/RepoCrypto.git "$HOME\Documents\WindowsPowerShell\Modules\RepoCrypto"
          
          cd ${{ env.DOTNET_ROOT}}\myapp
          Import-Module $HOME\Documents\WindowsPowerShell\Modules\RepoCrypto
          
          $key = 'mMXkoLZEfBk='
          Write-Host "Your Key is $($key)"
          Write-Host "$(Get-Date -f $timeStampFormat) - Replacing env appsettings file with encrypted one: In progress"
          Protect-File "appsettings.${{inputs.CLIENT_ENV}}.json" -Algorithm DES -KeyAsPlainText $key -RemoveSource

      - name: Upload build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: 'PACKAGE_${{ inputs.PROJECT_ROOT_DIRECTORY }}'
          path: '${{ env.DOTNET_ROOT}}/myapp'
          
      - name: Download build artifact
        if: ${{ inputs.DOWNLOAD_PACKAGE == 'true' }}
        uses: actions/download-artifact@v2.1.0
        with:
          name: 'PACKAGE_${{ inputs.PROJECT_ROOT_DIRECTORY }}'

      - name: Stop Application Pool
        if: ${{ inputs.DEPLOY_IIS == 'true' }}
        shell: cmd
        run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ inputs.SITE_NAME }}",recycleMode="StopAppPool",computerName="https://${{ inputs.SERVER_IP }}:${{ inputs.SERVER_PORT }}/msdeploy.axd?site=${{ inputs.SITE_NAME }}",username="LUG-TCAGENT\kevin",password="${{ secrets.WEBDEPLOY_PASSWORD }}",AuthType="Basic"'

      - name: Deploy to an IIS webserver
        if: ${{ inputs.DEPLOY_IIS == 'true' }}
        shell: cmd
        run: '"C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:contentPath="${{ env.DOTNET_ROOT}}/${{ inputs.PROJECT_ROOT_DIRECTORY }}" -dest:contentPath="${{ inputs.SITE_NAME }}",computerName="https://${{ inputs.SERVER_IP }}:${{ inputs.SERVER_PORT }}/msdeploy.axd?site=${{ inputs.SITE_NAME }}",username="${{ inputs.WEBDEPLOY_USER }}",password="${{ secrets.WEBDEPLOY_PASSWORD }}",authtype="Basic"'
      
      - name: Start Application Pool
        if: ${{ inputs.DEPLOY_IIS == 'true' }}
        shell: cmd
        run: '"C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:recycleApp -dest:recycleApp="${{ inputs.SITE_NAME }}",recycleMode="StartAppPool",computerName="https://${{ inputs.SERVER_IP }}:${{ inputs.SERVER_PORT }}/msdeploy.axd?site=${{ inputs.SITE_NAME }}",username="LUG-TCAGENT\kevin",password="${{ secrets.WEBDEPLOY_PASSWORD }}",AuthType="Basic"'
