#This workflow is used for all on-premise IDV deployments

name: Create a Javascript application build artifact OR deploy to the Laboremus Test environment.

on:
  workflow_call:
    inputs:
      CLIENT:
        type: string
      CLIENT_ENV:
        type: string
      DOWNLOAD_PACKAGE:
        type: string
      DEPLOY_IIS:
        type: string
      SITE_NAME:
        type: string   
      WEBDEPLOY_USER:
        type: string
      REPO_NAME:
        type: string
      DIST_FOLDER:
        type: string
      COMPUTER_NAME:
        type: string
    secrets:
      WEBDEPLOY_PASSWORD:
        required: true

jobs:
  Build-Package-Deploy:     #This job builds, packages and can also deploy to a laboremus environment
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    #- name: Test
    #  run: npm run test

    #This step creates a build for SFIs only
    - name: Build
      if: inputs.CLIENT_ENV != 'test' && inputs.CLIENT_ENV != 'staging' && inputs.CLIENT_ENV != 'Production'
      run: npm run build-${{inputs.CLIENT}}-${{inputs.CLIENT_ENV}}
      env:
        CI: ""
    
    #This step creates a build for one of the 4 laboremus environments 
    - name: Build
      if: inputs.CLIENT_ENV == 'test' || inputs.CLIENT_ENV == 'staging' || inputs.CLIENT_ENV == 'Production' || inputs.CLIENT_ENV == 'testLugtc'
      run: npm run build-${{inputs.CLIENT_ENV}}
      env:
        CI: ""
    
    #Uploads the artifact so that it can be downloaded as a ZIP
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.REPO_NAME}}-${{ inputs.CLIENT }}-${{ inputs.CLIENT_ENV }}
        path: ${{inputs.DIST_FOLDER}}
        
    #Deploys application to the Laboremus Test environment if the deployment option is selected.
    - name: Deploy
      if: ${{ inputs.DEPLOY_IIS == 'true' }}
      shell: cmd
      run: '"C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:contentPath="D:\a\${{inputs.REPO_NAME}}\${{inputs.REPO_NAME}}\${{inputs.DIST_FOLDER}}" -dest:contentPath="${{inputs.SITE_NAME}}",computerName="${{inputs.COMPUTER_NAME}}?site=${{inputs.SITE_NAME}}",username="${{inputs.WEBDEPLOY_USER}}",password="${{secrets.WEBDEPLOY_PASSWORD}}",authtype="Basic"'

