# This is a basic workflow to help you get started with Actions

name: NODE_CI/CD_ROOT_WORKFLOW

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        type: string
      APP_NAME:
        type: string
      COMPUTER_NAME:
        type: string
      WEBDEPLOY_USER:
        type: string
      SITE_NAME:
        type: string
      DIST_FOLDER:
        type: string
      WEBDEPLOY_PASSWORD:
        type: string

env:
  NODE_VERSION: '12.x'

jobs:
  build-and-deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: LOG_INFO
      run: |
        echo "${{inputs.APP_NAME}}"
        echo "${{inputs.WEBDEPLOY_USER}}"
        echo "${{inputs.WEBDEPLOY_PASSWORD}}"
        
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}
        
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install
      
    - name: Create Distribution for ${{inputs.APP_NAME}}
      run: |
        echo "BUILDING FOR ${{inputs.ENVIRONMENT}}"
        npm run build-${{inputs.ENVIRONMENT}}
      env:
        CI: ""
    - name: Deploy
      shell: cmd
      run: npm run deploy --autodatacapture-backoffice:ComputerName="https://154.0.128.234:18172/msdeploy.axd?site=Bou_NationalIdVerification_Auth_Ui_React" --autodatacapture-backoffice:UserName="kevin" --autodatacapture-backoffice:Password="8nJYcxLp4MLhkPQic" --autodatacapture-backoffice:sourcePath="build" --autodatacapture-backoffice:destPath="Bou_NationalIdVerification_Auth_Ui_React"
