name: Root_manual_node_workflow
on:
  workflow_call:
    inputs:
      CLIENT_ENV:
        type: string
      AZURE_WEBAPP_NAME:
        type: string
      AZURE_WEBAPP_PACKAGE_PATH:
        type: string
      SLOT_NAME:
        type: string
      REPO_NAME:
        type: string
      GITHUB_WORKSPACE:
        type: string
      BUILD_FOLDER:
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true
      AZURE_CREDENTIALS:
        required: true

jobs:
  Build-Package-IIS_Deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Distribution for ${{inputs.APP_NAME}}
      run:  mkdir ${{inputs.GITHUB_WORKSPACE}}/${{inputs.BUILD_FOLDER}}
      
    - name: copy * into ${{inputs.BUILD_FOLDER}}
      run: copy ${{inputs.GITHUB_WORKSPACE}} ${{inputs.GITHUB_WORKSPACE}}/${{inputs.BUILD_FOLDER}}
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.REPO_NAME}}-${{ inputs.CLIENT_ENV }}
        path: ${{inputs.BUILD_FOLDER}}
        
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: ${{inputs.REPO_NAME}}-${{ inputs.CLIENT_ENV }}
        
    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
         app-name: ${{ inputs.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package: ./${{inputs.REPO_NAME}}-${{ inputs.CLIENT_ENV }}
         slot-name: ${{ inputs.SLOT_NAME }}
