<<<<<<< HEAD
name: Javascript
=======
name: Deploy a Javascript application to the Azure cloud.

>>>>>>> release/Rename_Javascript_workflow
on:
  workflow_call:
    inputs:
      CLIENT_ENV:
        type: string
      AZURE_WEBAPP_NAME:
        type: string
      AZURE_WEBAPP_PACKAGE_PATH:
        type: string
      SLOT_NAME:
        type: string
      REPO_NAME:
        type: string
      BUILD_FOLDER:
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true
      AZURE_CREDENTIALS:
        required: true

jobs:
<<<<<<< HEAD
  Build-Package-IIS_Deploy:
=======
  Build-and-Deploy:
>>>>>>> release/Rename_Javascript_workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x.x
        #cache: 'npm'
        
<<<<<<< HEAD
    - name: Install the latest version of npm
=======
    - name: Install the latest npm version
>>>>>>> release/Rename_Javascript_workflow
      run: npm install -g npm@latest
      
    - name: Install dependencies
      run: npm install
      
<<<<<<< HEAD
    - name: Run unit tests
      run: npm test

    - name: Build the application
=======
    - name: Test
      run: npm test

    - name: Build
>>>>>>> release/Rename_Javascript_workflow
      run:  npm run build-${{inputs.CLIENT_ENV}}
      env:
        CI: ""
        
<<<<<<< HEAD
    - name: Show content
      run: dir
        
    - name: Azure Login
=======
    - name: Login
>>>>>>> release/Rename_Javascript_workflow
      uses: Azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
         app-name: ${{ inputs.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package: ${{inputs.BUILD_FOLDER}}
         slot-name: ${{ inputs.SLOT_NAME }}
