name: Root_manual_node_workflow
on:
  workflow_call:
    inputs:
      CLIENT:
        type: string
      CLIENT_ENV:
        type: string
      DOWNLOAD_PACKAGE:
        type: string
      DEPLOY_IIS:
        type: string
      SITE_NAME:
        type: string
      SERVER_IP:
        type: string
      SERVER_PORT:
        type: string   
      WEBDEPLOY_USER:
        type: string
    secrets:
      WEBDEPLOY_PASSWORD:
        required: true

jobs:
  Build-Package-IIS_Deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: npm install, build, and test
      run: |
        npm install
        npm run build-${{ inputs.CLIENT_ENV }} --if-present
        npm run test --if-present
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: AuthUI-${{ inputs.CLIENT }}-${{ inputs.CLIENT_ENV }}
        path: build
        
    - name: Download artifact from build job
      if: ${{ inputs.DOWNLOAD_PACKAGE == 'true' }}
      uses: actions/download-artifact@v2
      with:
        name: AuthUI-${{ inputs.CLIENT }}-${{ inputs.CLIENT_ENV }}
        
    - name: Deploy to an IIS webserver
      if: ${{ inputs.DEPLOY_IIS == 'false' }}
      run: npm run deploy --auth-service-ui-backoffice:ComputerName="https://${{ inputs.SERVER_IP }}:${{ inputs.SERVER_PORT }}/msdeploy.axd" --auth-service-ui-backoffice:UserName="${{ secrets.WEBDEPLOY_USER }}" --auth-service-ui-backoffice:Password="${{ secrets.WEBDEPLOY_PASSWORD }}" --auth-service-ui-backoffice:sourcePath="build" --auth-service-ui-backoffice:destPath="${{ inputs.SITE_NAME }}"
