name: Root_manual_node_workflow
on:
  workflow_call:
    inputs:
      CLIENT_ENV:
        type: string
      AZURE_WEBAPP_NAME:
        type: string
      AZURE_WEBAPP_PACKAGE_PATH:
        type: string
      SLOT_NAME:
        type: string
      REPO_NAME:
        type: string
      BUILD_FOLDER:
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true
      AZURE_CREDENTIALS:
        required: true

jobs:
  Build-Package-IIS_Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x.x
        #cache: 'npm'
        
    - name: Show version
      run: npm --version
      
    - name: Install dependencies
      run: npm install
      
    - name: Run unit tests
      run: npm test

    - name: Create Distribution
      run:  npm run build-${{inputs.CLIENT_ENV}}
      env:
        CI: ""
        
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.BUILD_FOLDER}}
        path: ${{inputs.BUILD_FOLDER}}
        
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: ${{inputs.BUILD_FOLDER}}
        
    - name: show content
      run: dir
        
    - name: Azure Login
      uses: Azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
         app-name: ${{ inputs.AZURE_WEBAPP_NAME }}
         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
         package: ${{inputs.BUILD_FOLDER}}
         slot-name: ${{ inputs.SLOT_NAME }}
