name: Push Nuget to Azure Artifacts

on:
  workflow_call:
    inputs:
      DOTNET_VERSION:
        type: string
      inputs.PROJECT_NAME:
        type: string
    secrets:
      NUGET_URL:
        required: true
      NUGET_TOKEN:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}
          source-url: ${{ secrets.NUGET_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

      - name: Restore
        run: |
          dotnet restore src/${{ inputs.PROJECT_NAME }}/${{ inputs.PROJECT_NAME }}.csproj

      - name: Build
        run: |
          dotnet build --no-restore src/${{ inputs.PROJECT_NAME }}/${{ inputs.PROJECT_NAME }}.csproj -c Release

      - name: Pack
        run: |
          dotnet pack src/${{ inputs.PROJECT_NAME }}/${{ inputs.PROJECT_NAME }}.csproj --no-restore -c Release

      - name: Publish
        run: |
          dotnet nuget push --api-key AzureArtifacts src/${{ inputs.PROJECT_NAME }}/bin/Release/*.nupkg
