#This workflow is used for all on-premise IDV deployments

name: Create a build artifact OR deploy to the Laboremus Test environment.

on:
  workflow_call:
    inputs:
      CLIENT:
        type: string
        required: true
      CLIENT_ENV:
        type: string
        required: true
      DOWNLOAD_PACKAGE:
        type: string
        required: true
      DEPLOY_IIS:
        type: string
        required: true
      SITE_NAME:
        type: string   
        required: true
      REPO_NAME:
        type: string
        required: true
      DIST_FOLDER:
        type: string
        required: true
      COMPUTER_NAME:
        type: string
        required: false
    secrets:
      WEBDEPLOY_PASSWORD:
        required: true
      WEBDEPLOY_USER:
        required: true
      SERVER_IP:
        required: true
      SERVER_PORT:
        required: true

jobs:
  Build-Package-Deploy:     #This job builds, packages and can also deploy to a laboremus environment
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.x.x
       # cache: 'npm'
        
    - name: Install the latest npm version
      run: npm install -g npm@latest
      
    - name: Install dependencies
      run: npm install --force or --legacy-peer-deps
    #- name: Test
    #  run: npm run test

    #This step creates a build for SFIs only
    - name: Build (SFI)
      if: inputs.CLIENT_ENV != 'test' && inputs.CLIENT_ENV != 'staging' && inputs.CLIENT_ENV != 'Production' && inputs.CLIENT_ENV != 'onprem'
      run: npm run build-${{inputs.CLIENT}}-${{inputs.CLIENT_ENV}}
      env:
        CI: ""
    
    #This step creates a build for one of the 4 laboremus environments 
    - name: Build (Laboremus)
      if: inputs.CLIENT_ENV == 'test' || inputs.CLIENT_ENV == 'staging' || inputs.CLIENT_ENV == 'Production' || inputs.CLIENT_ENV == 'testLugtc' || inputs.CLIENT_ENV == 'onprem'
      run: npm run build-${{inputs.CLIENT_ENV}}
      env:
        CI: ""
    
    #Uploads the artifact so that it can be downloaded as a ZIP
    - name: Upload build artifact
      if: ${{ inputs.DOWNLOAD_PACKAGE == 'true' }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{inputs.REPO_NAME}}-${{ inputs.CLIENT }}-${{ inputs.CLIENT_ENV }}
        path: ${{inputs.DIST_FOLDER}}
        
    #Deploys application to the Laboremus Test environment if the deployment option is selected.
    - name: Deploy
      if: ${{ inputs.DEPLOY_IIS == 'true' }}
      shell: cmd
      run: '"C:/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -allowUntrusted -source:contentPath="D:\a\${{inputs.REPO_NAME}}\${{inputs.REPO_NAME}}\${{inputs.DIST_FOLDER}}" -dest:contentPath="${{inputs.SITE_NAME}}",computerName="https://${{secrets.SERVER_IP}}:${{secrets.SERVER_PORT}}/msdeploy.axd?site=${{inputs.SITE_NAME}}",username="${{secrets.WEBDEPLOY_USER}}",password="${{secrets.WEBDEPLOY_PASSWORD}}",authtype="Basic"'

